### ISSUE TITLE
Add GT1 freq support

### ISSUE THREAD

**Issue by rodrigovivi** [ulissesf/qmassa#13]
Currently we are only looking at GT0, but we already have users that would like and need to look at GT1 freq behavior

**Comment by ulissesf** [comment]
Agreed. It was left as TODO in the code initially. I might have an idea on how to extend it easily.

**Comment by ulissesf** [comment]
I've made some changes in order to do this and organize the content in the UI. The table where we put all device stats was getting long for smaller terminal widths (like 80 cols), and drivers weren't reporting more than one frequency (for GT/GFX) so that also had to be extended. I'm merging all these changes now and for Xe/i915 I'm reading other frequencies (media on GT1) via sysfs.
